---
title: "A Quick Look at Crypto Currencies with R - Part 3 Rolling Correlations and More!"
author: "Dr. Aous Abdo @aousabdo"
output:
  html_notebook: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

In my two previous posts, [Downloading and Processing Crypto Data with R](http://rpubs.com/aousabdo/crypto_1) and [Corrleations in the Crypto World Part 1](http://rpubs.com/aousabdo/crypto_2) I went over how one can download crypto data in R and talked about static correlations for some coins. In this post, we will cover rolling correlatoins, a type of correlations we use with time-series data like crypto data. 

## Rolling Correlations

Establishing a relationship, in this case a correlation, between two time series can be very benificial for several reasons, the most important of which is to being able to use this relationship/correlation to predict market movement, which if you can get right then you'll be rich. Established correlations between the price of a crypto currency or a stock, for example, with other time series data such as market sentiment, news etc. can be used to better forecast the movement of that stock or coin. But as we have seen above, one problem exists, these correlations are not static and they could vary greatly overtime as we have seen in the examples above. 

